---
- hosts: all
  gather_facts: no
  become: true
  become_method: su
  become_user: root
  tasks:
    - name: Ensure Python is installed for Ansible
      raw: apt-get install -y python3
      changed_when: false
