---
- hosts: all
  gather_facts: no
  become: true
  become_method: su
  
  tasks:
    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600  # Reduces frequency of cache updates
